# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KonjoCommunities' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KonjoCommunities

  pod 'react-native-geolocation', path: '../node_modules/@react-native-community/geolocation'

end
