require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '10.0'

target 'KonjoCommunities' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  # target 'KonjoCommunitiesTests' do
  #   inherit! :complete
  #   # Pods for testing
  # end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

# target 'KonjoCommunities-tvOS' do
#   # Pods for RNTodo-tvOS

#   target 'KonjoCommunities-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end
# end